config/routes.rb
Rails.application.routes.draw do


  resources :topics do
    collection do
      post 'my_location'
    end
  	resources :messages
  end

  resources :users
  root to: 'visitors#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
end

app/models/message.rb
class Message < ActiveRecord::Base

	belongs_to :user
	belongs_to :topic
	
end

app/models/topic.rb
class Topic < ActiveRecord::Base

	belongs_to :user
	has_many :messages
	geocoded_by :address
	after_validation :geocode

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :topics
  has_many :messages

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
         user.name = auth['info']['name'] || ""
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  private
    def current_user
      begin
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      rescue Exception => e
        nil
      end
    end

    def user_signed_in?
      return true if current_user
    end

    def correct_user?
      @user = User.find(params[:id])
      unless current_user == @user
        redirect_to root_url, :alert => "Access denied."
      end
    end

    def authenticate_user!
      if !current_user
        redirect_to root_url, :alert => 'You need to sign in for access to this page.'
      end
    end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  before_action :set_topic

  # GET /messages
  # GET /messages.json
  def index
    @messages = @topic.messages
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.create!(message_params)
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_topic
      @topic = Topic.find_by_id(params[:topic_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:body, :user_id, :topic_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/facebook'
  end

  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'],
                      :uid => auth['uid'].to_s).first || User.create_with_omniauth(auth)
    reset_session
    session[:user_id] = user.id
    redirect_to root_url, :notice => 'Signed in!'
  end

  def destroy
    reset_session
    redirect_to root_url, :notice => 'Signed out!'
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
    @hash = Gmaps4rails.build_markers(@topics) do |topic, marker|
      marker.lat topic.latitude
      marker.lng topic.longitude
      marker.title topic.title
      marker.infowindow topic.description
    end
  end

  def my_location
    coordinates = params[:my_location]
    return if coordinates.blank?
    @near_topics = Topic.near(
      [coordinates['latitude'], coordinates['longitude']],
      coordinates['range'],
      :units => :km
    )
    render json: @near_topics
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new()
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      new_params = params.require(:topic).permit(:latitude, :longitude, :address, :description, :title)
      new_params[:latitude] = randomize_location(params[:topic][:latitude])
      new_params[:longitude] = randomize_location(params[:topic][:longitude])
      new_params
    end

    def randomize_location location
       result = location.to_s[0..6] + rand(0..99).to_s
       result
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :correct_user?, :except => [:index]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>
<% if user_signed_in? %>
  <li><%= link_to 'Sign out', signout_path %></li>
<% else %>
  <li><%= link_to 'Sign in', signin_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Hereiam" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Hereiam" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :topic_id %><br>
    <%= f.number_field :topic_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/_message.html.erb
<li>
  <span class="created_at"><%= message.created_at.strftime("%H:%M") %></span>
  -
  <%= message.body %>
</li>

app/views/messages/create.js.erb
$("#new_message")[0].reset(); 	
$('.chat-container [type=submit]').removeAttr('disabled', 'disabled')

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<h1>Chat window</h1>

<div class="chat-container">
  <ul id="chat">
    <%= render @messages %>
  </ul>

  <%= form_for [@topic, Message.new], remote: true do |f| %>
      <%= f.text_field :body %>
      <%= f.hidden_field :topic_id, value: @topic.id %>
      <%= f.hidden_field :user_id, value: current_user.try(:id) %>
      <%= f.submit "Send" %>
  <% end %>
</div>

<script>
  callUpdate(<%= @topic.id %>)
</script>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @message.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @message.user_id %>
</p>

<p>
  <strong>Topic:</strong>
  <%= @message.topic_id %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/trunk/richmarker/src/richmarker-compiled.js' type='text/javascript'></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script>

<h1>Listing topics</h1>

<table>
  <thead>
    <tr>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Address</th>
      <th>Description</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.latitude %></td>
        <td><%= topic.longitude %></td>
        <td><%= topic.address %></td>
        <td><%= topic.description %></td>
        <td><%= topic.title %></td>
        <td><%= link_to 'Show', topic %></td>
        <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
        <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>
<script>
  current_location = getLocation();
  buildMap(<%=raw nil.to_json %>);


  function loadNearPlaces(point) {
    $.ajax({
      dataType: 'JSON',
      url: '/topics/my_location',
      data:{
        my_location: {
          latitude: point.lat(),
          longitude: point.lng(),
          range: 20
        }
      },
      type: "POST",
      success: function (data) {
        markers = handler.addMarkers(data);
        handler.bounds.extendWith(markers);
      },
      error: function() {
        console.log('oops')
      }
    });
  }

  function newTopic(current_location) {
    $.ajax({
        url: '/topics',
        data:{
          topic: {
            latitude: current_location.lat(),
            longitude: current_location.lng(),
            title: 'New location'
          }
        },
        type: "POST",
        success: function () {
          console.log('ok');
        },
        error: function() {
          console.log('oops')
        }
    });
  }

</script>

<%= link_to 'New Topic', new_topic_path %>

app/views/topics/new.html.erb
<h1>New topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @topic.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @topic.longitude %>
</p>

<p>
  <strong>Address:</strong>
  <%= @topic.address %>
</p>

<p>
  <strong>Description:</strong>
  <%= @topic.description %>
</p>

<p>
  <strong>Title:</strong>
  <%= @topic.title %>
</p>

<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>